[mirror]
name = '菠萝云'
description = 'Edgeless 官方主站点'
root = 'https://pineapple.edgeless.top/'
services = [
    {name="plugins",path="disk/插件包/",local='./test/packages'},
    {name="iso",path="disk/Socket/",local='I:\Edgeless\OneDrive - 洛阳科技职业学院\Socket'},
    {name="alpha",path="disk/Socket/Alpha/",local='I:\Edgeless\OneDrive - 洛阳科技职业学院\Socket\Alpha'},
    {name="ventoy",path="disk/Socket/Ventoy/",local='D:\Download\HubCache\Burn'},
    {name="hub",path="disk/Socket/Hub/",local='I:\Edgeless\OneDrive - 洛阳科技职业学院\Socket\Hub'},
]

[property]
native_server = true
upload_bandwidth = 1000
sync_interval = 0
official_maintained = true


# 外部配置应是一个json文件，会被直接呈现到api接口相应位置
[config]
hub = 'I:\Edgeless\OneDrive - 洛阳科技职业学院\Socket\Hub\Update\update.json'
notice = 'I:\Edgeless\OneDrive - 洛阳科技职业学院\Socket\Hub\notice.json'
alpha_cover = 'I:\Edgeless\OneDrive - 洛阳科技职业学院\Socket\Alpha\alpha.json'

[token]
alpha = 'ALPHA'
super_user = 'SUPER_USER'